"""Trading signal data models"""

from enum import Enum
from typing import Optional
from pydantic import BaseModel, Field


class SignalType(str, Enum):
    """Signal types"""
    BUY = "BUY"
    SELL = "SELL"
    HOLD = "HOLD"
    CLOSE_LONG = "CLOSE_LONG"
    CLOSE_SHORT = "CLOSE_SHORT"


class SignalData(BaseModel):
    """
    Trading signal data model
    
    Represents a trading signal generated by a strategy
    """
    
    strategy_name: str = Field(..., description="Strategy identifier (e.g., 'dual_ma')")
    symbol: str = Field(..., description="Trading pair symbol (e.g., 'BTCUSDT')")
    timestamp: int = Field(..., description="Unix timestamp in seconds")
    signal_type: SignalType = Field(..., description="Signal type (BUY/SELL/HOLD)")
    price: float = Field(..., description="Current price when signal generated")
    reason: str = Field(..., description="Reason for signal generation")
    
    # Optional fields for advanced signals
    confidence: Optional[float] = Field(None, description="Signal confidence (0.0-1.0)")
    stop_loss: Optional[float] = Field(None, description="Suggested stop loss price")
    take_profit: Optional[float] = Field(None, description="Suggested take profit price")
    position_size: Optional[float] = Field(None, description="Suggested position size")
    
    class Config:
        json_schema_extra = {
            "example": {
                "strategy_name": "dual_ma",
                "symbol": "BTCUSDT",
                "timestamp": 1705320000,
                "signal_type": "BUY",
                "price": 35200.0,
                "reason": "MA5(35250.0) crossed above MA20(35100.0)",
                "confidence": 0.75,
                "stop_loss": 34800.0,
                "take_profit": 36000.0
            }
        }
    
    def __repr__(self) -> str:
        return (
            f"<SignalData {self.signal_type.value} {self.symbol} "
            f"@ {self.price:.2f} "
            f"by {self.strategy_name}>"
        )


class PositionData(BaseModel):
    """
    Position data model
    
    Represents an open position
    """
    
    symbol: str = Field(..., description="Trading pair symbol")
    side: str = Field(..., description="Position side (LONG/SHORT)")
    entry_price: float = Field(..., description="Entry price")
    current_price: float = Field(..., description="Current price")
    quantity: float = Field(..., description="Position quantity")
    unrealized_pnl: float = Field(..., description="Unrealized profit/loss")
    unrealized_pnl_pct: float = Field(..., description="Unrealized PnL percentage")
    entry_time: int = Field(..., description="Entry timestamp")
    
    class Config:
        json_schema_extra = {
            "example": {
                "symbol": "BTCUSDT",
                "side": "LONG",
                "entry_price": 35000.0,
                "current_price": 35200.0,
                "quantity": 0.5,
                "unrealized_pnl": 100.0,
                "unrealized_pnl_pct": 0.57,
                "entry_time": 1705320000
            }
        }


class OrderData(BaseModel):
    """
    Order data model
    
    Represents a trading order (for backtesting or live trading)
    """
    
    order_id: str = Field(..., description="Order ID")
    symbol: str = Field(..., description="Trading pair symbol")
    side: str = Field(..., description="Order side (BUY/SELL)")
    order_type: str = Field(..., description="Order type (MARKET/LIMIT)")
    price: Optional[float] = Field(None, description="Order price (for LIMIT orders)")
    quantity: float = Field(..., description="Order quantity")
    status: str = Field(..., description="Order status (PENDING/FILLED/CANCELLED)")
    filled_quantity: float = Field(0.0, description="Filled quantity")
    average_price: Optional[float] = Field(None, description="Average fill price")
    timestamp: int = Field(..., description="Order timestamp")
    
    class Config:
        json_schema_extra = {
            "example": {
                "order_id": "12345",
                "symbol": "BTCUSDT",
                "side": "BUY",
                "order_type": "LIMIT",
                "price": 35000.0,
                "quantity": 0.5,
                "status": "FILLED",
                "filled_quantity": 0.5,
                "average_price": 35000.0,
                "timestamp": 1705320000
            }
        }

